### ISSUE TITLE
페이지 퍼블리싱

### ISSUE THREAD

**Issue by imdaxsz** [imdaxsz/yummy#6]
## 📝 개요

페이지 퍼블리싱

## ✅ TODO
- [x] 메인 페이지 퍼블리싱
   - [x] 검색 모달 퍼블리싱
- [x] 리스트 상세 페이지 퍼블리싱
- [x] 보관함 페이지 퍼블리싱
- [x] 에디터 퍼블리싱
- [x] 글 상세페이지 퍼블리싱
